const CACHE='aseel-v6';
self.addEventListener('install',e=>self.skipWaiting());
self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));
self.addEventListener('fetch',e=>{
  if(!e.request.url.endsWith('/index.html')&&!e.request.url.endsWith('/'))return;
  e.respondWith((async()=>{
    const r=await fetch(e.request);let t=await r.text();
    const inject=`<script src="https://www.gstatic.com/firebasejs/10.14.1/firebase-app-compat.js"></script><script src="https://www.gstatic.com/firebasejs/10.14.1/firebase-auth-compat.js"></script><script src="https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore-compat.js"></script><script>(function(){const C={apiKey:"AIzaSyCKW9_6dZXJony37x9Ly-6-rWpb1WZF7XVg",authDomain:"aseel-warehouse.firebaseapp.com",projectId:"aseel-warehouse",storageBucket:"aseel-warehouse.firebasestorage.app",messagingSenderId:"533394002034",appId:"1:533394002034:web:cc308c30a25cdceadaf2eb"};firebase.initializeApp(C);const db=firebase.firestore(),N={products:'products',orders:'orders',customers:'customers',packers:'packers'};const D=[{id:'p1',name:'مبخرة 3-4'},{id:'p2',name:'مبخرة كريستال'},{id:'p3',name:'دخون كمبودي'},{id:'p4',name:'عود معطر درجة أولى'},{id:'p5',name:'بخور مستكة'},{id:'p6',name:'دهن عود ملكي'}];window.__fs={products:D.slice(),orders:[],customers:[],packers:[]};window.get=(k,d)=>window.__fs[k]||d;window.put=async()=>{for(const k in N){const ref=db.collection(N[k]);for(const x of window.__fs[k])await ref.doc(x.id).set(x,{merge:true})}};function sync(k){db.collection(N[k]).onSnapshot(s=>{const a=s.docs.map(d=>({id:d.id,...d.data()}));const target=window.__fs[k];if(a.length){target.splice(0,target.length,...a)}else if(k==='products'&&target.length===0){target.push(...D)}if(window.render)setTimeout(()=>window.render(),0)},e=>{console.error('Firestore '+k,e);alert('Firestore '+k+': '+(e.code||'unknown')+'\\n'+(e.message||e))})}firebase.auth().signInAnonymously().then(async()=>{for(const k in N){const s=await db.collection(N[k]).get();if(s.docs.length)window.__fs[k].splice(0,window.__fs[k].length,...s.docs.map(d=>({id:d.id,...d.data()})))}if(!window.__fs.products.length){window.__fs.products.push(...D);await window.put()}sync('products');sync('orders');sync('customers');sync('packers');if(window.render)window.render()}).catch(e=>{console.error('Firebase:',e);alert('Firebase: '+(e.code||'unknown')+'\\n'+(e.message||e))})})()</script>`;
    t=t.replace('</head>',inject+'</head>');
    t=t.replace(/function get\(k,d\)\{try\{return JSON\.parse\(localStorage\.getItem\('mk_'\+k\)\)\?\?d\}catch\{return d\}\}function put\(\)\{localStorage\.setItem\('mk_products',JSON\.stringify\(products\)\);localStorage\.setItem\('mk_orders',JSON\.stringify\(orders\)\);localStorage\.setItem\('mk_customers',JSON\.stringify\(customers\)\);localStorage\.setItem\('mk_packers',JSON\.stringify\(packers\)\)\}/,'function get(k,d){return window.get(k,d)}function put(){window.__fs.products=products;window.__fs.orders=orders;window.__fs.customers=customers;window.__fs.packers=packers;return window.put()}');
    return new Response(t,{headers:r.headers});
  })());
});